--- #YAML:1.0
name:               Pick-TCL
version:            0.04
abstract:           class to run commands in a Pick TCL shell
author:
    - Jack Burton <jack@saosce.com.au>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    IPC::Run:    0
    Test::More:  0
requires:
    Carp:  0
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    local_pick:
        description:  Connect to a local Pick VM without ssh
        requires:
            IPC::Run:  0
    remote_pick:
        description:  Connect to a Pick VM over ssh
        requires:
            Net::OpenSSH:  0
